name: Minetest Tutorial and Documentation
description: Simple and easy to understand tutorial book
author: rubenwardy and contributors
permalink: pretty
absolute_url: http://rubenwardy.github.io/minetest_doc
url: /minetest_doc
